name: 'Is Changed'
description: 'Did the entity changed in the commit?'
author: 'Saionaro <shibakow@gmail.com>'
branding:
  icon: help-circle
  color: blue
inputs:
  glob:
    description: 'A glob template to be checked'
    required: true
  token:
    description: 'Github token to grant access to commits history'
    required: true
outputs:
  changed:
    description: 'Whether one of input entities changed or not'
runs:
  using: 'node16'
  main: 'dist/index.js'
