name: CI

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci && npm run build
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'dist'
          message: 'chore: automatic build [skip ci]'
          default_author: github_actions
      # - run: npm run release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
